In [54]:
import numpy as np
import pandas as pd

In [55]:
dataset=pd.read_csv('C:/Users/hp/Desktop/Untitled Folder/Predict weight based on height and gender/weight-height.csv')

In [56]:
dataset

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [57]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  10000 non-null  object 
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


In [58]:
dataset.describe()

Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [59]:
dataset.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [61]:
X=dataset.iloc[:,:-1].values
X

array([['Male', 73.847017017515],
       ['Male', 68.7819040458903],
       ['Male', 74.1101053917849],
       ...,
       ['Female', 63.8679922137577],
       ['Female', 69.0342431307346],
       ['Female', 61.9442458795172]], dtype=object)

In [62]:
Y=dataset.iloc[:,-1].values
Y

array([241.89356318, 162.31047252, 212.74085556, ..., 128.47531878,
       163.85246135, 113.64910268])

In [63]:
from sklearn.preprocessing import LabelEncoder
gender_le=LabelEncoder()

In [66]:
X[:,0]=gender_le.fit_transform(X[:,0])

In [67]:
X[:,0]

array([1, 1, 1, ..., 0, 0, 0], dtype=object)

In [68]:
X

array([[1, 73.847017017515],
       [1, 68.7819040458903],
       [1, 74.1101053917849],
       ...,
       [0, 63.8679922137577],
       [0, 69.0342431307346],
       [0, 61.9442458795172]], dtype=object)

In [71]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [72]:
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(X_train,Y_train)

LinearRegression()

In [73]:
pred=lin_reg.predict(X_test)

In [75]:
my_weight_pred=lin_reg.predict([[0,12]])

In [79]:
from sklearn import metrics

In [80]:
print("R2 score =",metrics.r2_score(Y_test,pred))
print("Mean Squared Error =",metrics.mean_squared_error(Y_test,pred))
print("Mean Absolute Error =",metrics.mean_absolute_error(Y_test,pred))

R2 score = 0.9017457495522369
Mean Squared Error = 102.39646885019076
Mean Absolute Error = 8.092055004104234


In [82]:
my_weight_pred = lin_reg.predict([[0,72]])
print('My predicted weight = ',my_weight_pred)

My predicted weight =  [185.33529161]
